/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type FileCategory = { 'pdf' : null } |
  { 'audio' : null } |
  { 'other' : null } |
  { 'video' : null } |
  { 'heic' : null } |
  { 'photo' : null };
export interface FileMetadata {
  'originalFilename' : string,
  'blob' : ExternalBlob,
  'mimeType' : string,
  'uploadTimestamp' : Time,
  'exifCaptureTimestamp' : [] | [Time],
  'fileId' : string,
  'category' : FileCategory,
  'sizeBytes' : bigint,
  'folderId' : [] | [string],
}
export interface Folder {
  'name' : string,
  'createdAt' : Time,
  'folderId' : string,
}
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'createFolder' : ActorMethod<[string, string], Folder>,
  'deleteFile' : ActorMethod<[string], undefined>,
  'deleteFiles' : ActorMethod<[Array<string>], undefined>,
  'deleteFolder' : ActorMethod<[string], undefined>,
  'getFileMetadata' : ActorMethod<[string], FileMetadata>,
  'listFiles' : ActorMethod<[[] | [string]], Array<FileMetadata>>,
  'listFolders' : ActorMethod<[], Array<Folder>>,
  'moveFileToFolder' : ActorMethod<[string, [] | [string]], FileMetadata>,
  'renameFolder' : ActorMethod<[string, string], Folder>,
  'uploadFile' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      [] | [Time],
      FileCategory,
      ExternalBlob,
      [] | [string],
    ],
    FileMetadata
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];