/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Folder = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'folderId' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileCategory = IDL.Variant({
  'pdf' : IDL.Null,
  'audio' : IDL.Null,
  'other' : IDL.Null,
  'heic' : IDL.Null,
  'photo' : IDL.Null,
});
export const FileMetadata = IDL.Record({
  'originalFilename' : IDL.Text,
  'blob' : ExternalBlob,
  'mimeType' : IDL.Text,
  'uploadTimestamp' : Time,
  'exifCaptureTimestamp' : IDL.Opt(Time),
  'fileId' : IDL.Text,
  'category' : FileCategory,
  'sizeBytes' : IDL.Nat,
  'folderId' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'createFolder' : IDL.Func([IDL.Text, IDL.Text], [Folder], []),
  'deleteFile' : IDL.Func([IDL.Text], [], []),
  'deleteFiles' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'deleteFolder' : IDL.Func([IDL.Text], [], []),
  'getFileMetadata' : IDL.Func([IDL.Text], [FileMetadata], ['query']),
  'listFiles' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(FileMetadata)],
      ['query'],
    ),
  'listFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
  'moveFileToFolder' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [FileMetadata],
      [],
    ),
  'renameFolder' : IDL.Func([IDL.Text, IDL.Text], [Folder], []),
  'uploadFile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(Time),
        FileCategory,
        ExternalBlob,
        IDL.Opt(IDL.Text),
      ],
      [FileMetadata],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Folder = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'folderId' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileCategory = IDL.Variant({
    'pdf' : IDL.Null,
    'audio' : IDL.Null,
    'other' : IDL.Null,
    'heic' : IDL.Null,
    'photo' : IDL.Null,
  });
  const FileMetadata = IDL.Record({
    'originalFilename' : IDL.Text,
    'blob' : ExternalBlob,
    'mimeType' : IDL.Text,
    'uploadTimestamp' : Time,
    'exifCaptureTimestamp' : IDL.Opt(Time),
    'fileId' : IDL.Text,
    'category' : FileCategory,
    'sizeBytes' : IDL.Nat,
    'folderId' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'createFolder' : IDL.Func([IDL.Text, IDL.Text], [Folder], []),
    'deleteFile' : IDL.Func([IDL.Text], [], []),
    'deleteFiles' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'deleteFolder' : IDL.Func([IDL.Text], [], []),
    'getFileMetadata' : IDL.Func([IDL.Text], [FileMetadata], ['query']),
    'listFiles' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(FileMetadata)],
        ['query'],
      ),
    'listFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
    'moveFileToFolder' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [FileMetadata],
        [],
      ),
    'renameFolder' : IDL.Func([IDL.Text, IDL.Text], [Folder], []),
    'uploadFile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(Time),
          FileCategory,
          ExternalBlob,
          IDL.Opt(IDL.Text),
        ],
        [FileMetadata],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };